// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"time"
)

type Link struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

type LinkVisit struct {
	ID        int64     `json:"id"`
	LinkID    int64     `json:"link_id"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	Referer   string    `json:"referer"`
	Status    int32     `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}
